{"name": "test_empty_user[chrome]", "status": "broken", "statusDetails": {"message": "ExceptionGroup: errors while tearing down <Session  exitstatus=<ExitCode.OK: 0> testsfailed=20 testscollected=32> (3 sub-exceptions)", "trace": "+ Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 344, in from_call\n  |     result: TResult | None = func()\n  |                              ~~~~^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 246, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |     ~~~~~~~~~~~~~~^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\logging.py\", line 858, in pytest_runtest_teardown\n  |     yield\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |     ~~~~~~~~~~~~~~^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |            ~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |           ^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |     ~~~~~~~~~~~~~~^^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\capture.py\", line 905, in pytest_runtest_teardown\n  |     return (yield)\n  |             ^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 193, in pytest_runtest_teardown\n  |     item.session._setupstate.teardown_exact(nextitem)\n  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 557, in teardown_exact\n  |     raise exceptions[0]\n  | ExceptionGroup: errors while tearing down <Session  exitstatus=<ExitCode.OK: 0> testsfailed=20 testscollected=32> (3 sub-exceptions)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 546, in teardown_exact\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1058, in finish\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |     ~~~~^^^^\n    |   File \"C:\\Users\\dhamyan\\PycharmProjects\\PythonProject\\PythonProject\\Automated-testing-project\\conftest.py\", line 46, in browser_driver\n    |     if not request.node.passed:\n    |            ^^^^^^^^^^^^^^^^^^^\n    | AttributeError: 'Session' object has no attribute 'passed'\n    +---------------- 2 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 546, in teardown_exact\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1058, in finish\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |     ~~~~^^^^\n    |   File \"C:\\Users\\dhamyan\\PycharmProjects\\PythonProject\\PythonProject\\Automated-testing-project\\conftest.py\", line 46, in browser_driver\n    |     if not request.node.passed:\n    |            ^^^^^^^^^^^^^^^^^^^\n    | AttributeError: 'Session' object has no attribute 'passed'\n    +---------------- 3 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\runner.py\", line 546, in teardown_exact\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1058, in finish\n    |     fin()\n    |     ~~~^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |     ~~~~^^^^\n    |   File \"C:\\Users\\dhamyan\\PycharmProjects\\PythonProject\\PythonProject\\Automated-testing-project\\conftest.py\", line 46, in browser_driver\n    |     if not request.node.passed:\n    |            ^^^^^^^^^^^^^^^^^^^\n    | AttributeError: 'Session' object has no attribute 'passed'\n    +------------------------------------"}, "attachments": [{"name": "stdout", "source": "bd542f31-540d-4283-9273-bb3ed76085ac-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser_driver", "value": "'chrome'"}], "start": 1759173830091, "stop": 1759173830410, "uuid": "b6d92639-1176-4fcc-aaf3-bda0e8028486", "historyId": "8564ff3ba34c2ebc938115198268dc1a", "testCaseId": "3603c99451753e9e0ab5d6d1e9a36fc8", "fullName": "test_login#test_empty_user", "labels": [{"name": "suite", "value": "test_login"}, {"name": "host", "value": "Jerry"}, {"name": "thread", "value": "27308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}], "titlePath": ["test_login.py"]}